# For Supabase CLI local development
project_id = "debtnote"

[api]
enabled = true

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]

[storage]
enabled = true
